channels:
- conda-forge
dependencies:
- python=3.13.2
- pip
- pip:
  - mlflow==3.0.0rc3
  - cloudpickle==3.1.1
  - numpy==2.2.6
  - pandas==2.2.3
  - scikit-learn==1.6.1
  - scipy==1.15.3
name: mlflow-env
