[project]
name = "mlflow-practice"
version = "0.1.0"
description = "MLflow 실험 프로젝트"
requires-python = ">=3.10"
dependencies = [
    "mlflow>=3.0.0rc2",
    "psycopg2-binary",
    "pandas",
    "scikit-learn",
]
